### PR TITLE
Feature/final data output

### PR DESCRIPTION
**Pull request by Lord-Kanzler**
## Description ##

**Endpoint for final data output to web backend, and cleaned/merged (almost final) dataset for B2P.**
- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [x] Have you added two reviewers to this pull request?
- [ ] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Comment by pingao2019** [comment]
Looks good!

**Comment by Lord-Kanzler** [comment]
[Set up final_data and final_data/extended endpoints to return clean and merged data.](https://trello.com/c/xIGbb4nH/59-set-up-finaldata-and-finaldata-extended-endpoints-to-return-clean-and-merged-data)

**Comment by pingao2019** [comment]
Good job!

**Review by pingao2019 — APPROVED** [review]
All looks good!

**Review by jakekrafczyk — APPROVED** [review]
Looks good

**Pull request merged**
