### PR TITLE
merged community served columns to one

### PR DESCRIPTION
**Pull request by pingao2019**
## Description ##

Clearly documents the reason for the pull request and what has changed.
- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Have you added two reviewers to this pull request?
- [ ] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Comment by Lord-Kanzler** [comment]
[Data Cleaning/ DS repo documentation review](https://trello.com/c/U8oTUWyF/19-data-cleaning-ds-repo-documentation-review)

**Review by Lord-Kanzler — CHANGES_REQUESTED** [review]
Looks good, but please remove Community Merged Columns. Also please add some comments in the document.

**Review by Lord-Kanzler — DISMISSED** [review]

**Review by jakekrafczyk — CHANGES_REQUESTED** [review]
The community_served column has some NaNs where there should be communities listed. Looks like its reading in the NaNs from the first 5 community served columns

**Comment by pingao2019** [comment]
merged 5 Community Served columns, suggest to drop Community served 6 to 10 because they all are null  value, no useful. Also suggest to drop some duplicated Project Code(97).

**Review by jakekrafczyk — APPROVED** [review]
Looks good, no more NaNs!

**Review by jessicagertig — APPROVED** [review]
Excellent discussion.  Anyone reviewing this pull request can view other team member comments to view information about changes made in this pull request.

**Pull request merged**
