### PR TITLE
Feature/final data output

### PR DESCRIPTION
**Pull request by Lord-Kanzler**
## Description ##

**changed data URL to work from main branch**
- [ ] This is a bugfix.
- [ ] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [ ] Have you linked this pull request to a Trello card?

## Review ##

- [x] Have you added two reviewers to this pull request?
- [x] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Review by jakekrafczyk — DISMISSED** [review]
Good work

**Review by pingao2019 — DISMISSED** [review]
Excellent Job!

**Review by jessicagertig — DISMISSED** [review]
Sorry, I was on the wrong pull request when I made my original comment.

**Comment by Lord-Kanzler** [comment]
I changed data URL to work from main branch, needs to be reviewed again.

**Review by pingao2019 — APPROVED** [review]
Good to me!

**Review by jakekrafczyk — APPROVED** [review]
Nice!

**Pull request merged**
