### PR TITLE
Feature/ds endpoints sites villages

### PR DESCRIPTION
**Pull request by Lord-Kanzler**
## Description ##

- Adding /sites endpoint to return clean (based on 08252020 status) site_assessment information. 
- Adding /villages endpoint to return clean (based on 08252020 status) gov. village and ID information. 
- Consolidating /raw files into this commit/pull request, to fit the same file structure, and allowing easier merging. 
 
- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [x] Have you added two reviewers to this pull request?
- [ ] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Comment by Lord-Kanzler** [comment]
[Setting up /sites and /villages endpoints to return clean site_assesement and gov. village name/IDs data.](https://trello.com/c/NdcZjQ1f/40-setting-up-sites-and-villages-endpoints-to-return-clean-siteassesement-and-gov-village-name-ids-data)

**Comment by Lord-Kanzler** [comment]
Should be relatively straightforward to review. The .CSV datasets are based of the latest notebook. Please pay attention to raw.py, sites.py, villages.py in project/app/api 

The URL to datasets will require modification after everything is merged on main branch.

**Comment by pingao2019** [comment]
I saw your post, your codes run pretty well. After review your codes, your codes are  clean and organized well, and no duplicated and unnecessary codes. Only add a little more comments maybe let readers read fast and easily.

**Review by jakekrafczyk — APPROVED** [review]
Looks good to me

**Review by pingao2019 — APPROVED** [review]
Excellent job, everything is good!

**Pull request merged**
