### PR TITLE
Feature/remove duplicated

### PR DESCRIPTION
**Pull request by pingao2019**
## Description ##

Clearly documents the reason for the pull request and what has changed.
- [ ] This is a bugfix.
- [ ] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Have you added two reviewers to this pull request?
- [ ] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Comment by pingao2019** [comment]
[Merging "site_assessment" and "names_codes" datasets](https://trello.com/c/FpunfeOD/20-merging-siteassessment-and-namescodes-datasets)

**Comment by pingao2019** [comment]
Maybe ready to be merged

**Review by Lord-Kanzler — CHANGES_REQUESTED** [review]
- project/app/api/__init__.py and project/app/api/hello.py should be part of a separate commit/pull request as they have nothing to do with data cleaning or duplicate removal.

- hello.py does not contribute, to B2P project and should not be on added to main if I remember what Ryan said correctly. No non-function code, and no commented out code in production repo.

- Please also change the pull request to part of a feature, since it's not a new feature.

I'll review the committed notebook after I finish writing the README.md for endpoints, otherwise if I pull current status, it might be overwritten locally.

**Comment by pingao2019** [comment]
Changed according to reviewer's comments

**Pull request closed without merging**
